FROM eclipse-temurin:8-jdk
WORKDIR /app

RUN apt-get update && apt-get install -y \
    fonts-dejavu-core \
    fonts-liberation \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p libs && \
    curl -sL https://archive.apache.org/dist/pdfbox/2.0.31/pdfbox-app-2.0.31.jar \
         -o libs/pdfbox-app-2.0.31.jar && \
    curl -sL https://repo1.maven.org/maven2/commons-fileupload/commons-fileupload/1.5/commons-fileupload-1.5.jar \
         -o libs/commons-fileupload-1.5.jar && \
    curl -sL https://repo1.maven.org/maven2/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar \
         -o libs/commons-io-2.15.1.jar && \
    curl -sL https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar \
         -o libs/javax.servlet-api-3.1.0.jar

COPY idl/ idl/
COPY src/ src/
COPY static/ static/
COPY start.sh .

RUN mkdir -p src/PDFForge classes outputs && \
    idlj -fall -td src idl/PDFService.idl && \
    javac -cp "libs/*" \
      src/PDFForge/*.java \
      src/corba/PDFWorkerImpl.java \
      src/corba/PDFWorkerServer.java \
      src/server/PDFHttpGateway.java \
      src/MultipartData.java \
      -d classes && \
    chmod +x start.sh

ENV PORT=10000 \
    CORBA_NS_HOST=localhost \
    CORBA_NS_PORT=1050

EXPOSE 10000
CMD ["./start.sh"]
